name: pulse2
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2023.01.10
  - certifi=2023.5.7
  - cffi=1.14.0
  - chardet=3.0.4
  - cpuonly=2.0
  - cryptography=2.9.2
  - cudatoolkit=11.0.221
  - cycler=0.10.0
  - freetype=2.9.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=2.9
  - intel-openmp=2019.4
  - jpeg=9b
  - kiwisolver=1.2.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.44.2
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1t
  - pandas=1.0.3
  - pip=20.0.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.2
  - pytorch-mutex=1.0
  - pytz=2020.1
  - qt=5.9.7
  - requests=2.23.0
  - setuptools=46.2.0
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tornado=6.0.4
  - typing_extensions=4.5.0
  - urllib3=1.25.8
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - colorama==0.4.6
    - dataclasses==0.6
    - dlib==19.19.0
    - future==0.18.3
    - joblib==1.2.0
    - ninja==1.11.1
    - numpy==1.24.3
    - pillow==9.5.0
    - scikit-learn==1.0
    - scipy==1.10.1
    - threadpoolctl==3.1.0
    - torch==1.7.1+cu110
    - torchaudio==0.7.2
    - torchvision==0.8.2+cu110
    - tqdm==4.62.0
